name: Deploy IoT Core Stack

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod

env:
  AWS_REGION: us-east-2
  NODE_VERSION: "18"

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install root dependencies
        run: npm ci

      - name: Install CDK dependencies
        run: |
          cd cdk
          npm ci

      - name: Install Lambda getMessages dependencies
        run: |
          cd lambda/getMessages
          npm ci

      - name: Install Lambda ackMessages dependencies
        run: |
          cd lambda/ackMessages
          npm ci

      - name: CDK Synth (Generate CloudFormation)
        run: |
          cd cdk
          npx cdk synth

      - name: CDK Diff
        run: |
          cd cdk
          npx cdk diff
        continue-on-error: true

      - name: CDK Deploy
        run: |
          cd cdk
          npx cdk deploy --require-approval never --outputs-file ../cdk-outputs.json
        if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'

      - name: Upload CDK outputs
        uses: actions/upload-artifact@v4
        with:
          name: cdk-outputs-${{ github.sha }}
          path: cdk-outputs.json
          retention-days: 30
        if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
